// This file is auto-generated by the App-Builder Contract System
// It must match the backend Pydantic models.

export interface Project {
  id: string;
  name: string;
  description?: string;
  status?: string;
  client_name: string;
  deadline: string;
  budget?: number;
  priority?: number;
  created_at?: string;
}