// This file is auto-generated by the App-Builder Contract System
// It must match the backend Pydantic models.

export interface Customer {
  id: string;
  email: string;
  name: string;
  phone?: string;
  company?: string;
  industry?: string;
  website?: string;
  country?: string;
  state?: string;
  city?: string;
  lead_score?: number;
  last_contact_date?: string;
  next_contact_date?: string;
  notes?: string;
  stage?: string;
  source?: string;
  preferred_contact_method?: string;
  preferred_contact_time?: string;
  automation_status?: string;
  ai_analysis?: string;
  created_at?: string;
}
