# YAML linting configuration
---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: true
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

ignore: |
  output/
  htmlcov/
  node_modules/
  .venv/
  venv/
