"""App Generator Service - Core app generation logic."""
import os
import asyncio
from typing import AsyncGenerator, Dict, Any, Optional, List
from dataclasses import dataclass
from pathlib import Path

try:
    import anthropic
    HAS_ANTHROPIC = True
except ImportError:
    HAS_ANTHROPIC = False

from .templates import TemplateManager
from .templates_fastapi import FastAPITemplateManager


@dataclass
class GenerationProgress:
    """Progress update during app generation."""
    step: str
    progress: int
    message: str
    files_generated: int = 0
    total_files: int = 0
    error: Optional[str] = None


class AppGeneratorService:
    """Service for generating applications from user ideas."""
    
    def __init__(self):
        self.template_manager = TemplateManager()
        self.fastapi_manager = FastAPITemplateManager()
        self.anthropic_key = os.getenv("ANTHROPIC_API_KEY")
    
    async def generate_app(
        self,
        idea: str,
        app_name: str,
        framework: str = "fastapi",
        features: Optional[List[str]] = None
    ) -> AsyncGenerator[GenerationProgress, None]:
        """Generate an application from user idea."""
        features = features or []
        
        try:
            yield GenerationProgress(step="analysis", progress=10, message="Analyzing your idea...")
            await asyncio.sleep(0.5)
            
            yield GenerationProgress(step="architecture", progress=20, message="Designing architecture...")
            architecture = await self._generate_architecture(idea, features)
            await asyncio.sleep(0.5)
            
            yield GenerationProgress(step="generation", progress=40, message="Generating code files...")
            
            if framework == "fastapi":
                files = await self._generate_fastapi_app(app_name, architecture, idea)
            else:
                files = await self._generate_flask_app(app_name, architecture, idea)
            
            total_files = len(files)
            for i, (filepath, content) in enumerate(files.items()):
                yield GenerationProgress(
                    step="generation",
                    progress=40 + int((i + 1) / total_files * 30),
                    message=f"Generated {filepath}",
                    files_generated=i + 1,
                    total_files=total_files
                )
                await asyncio.sleep(0.1)
            
            yield GenerationProgress(step="validation", progress=80, message="Validating code...")
            await asyncio.sleep(0.3)
            
            yield GenerationProgress(
                step="complete",
                progress=100,
                message="App generation complete!",
                files_generated=total_files,
                total_files=total_files
            )
            
        except Exception as e:
            yield GenerationProgress(step="error", progress=0, message="Generation failed", error=str(e))
    
    async def _generate_architecture(self, idea: str, features: List[str]) -> Dict[str, Any]:
        """Generate application architecture based on idea."""
        if self.anthropic_key and HAS_ANTHROPIC:
            try:
                client = anthropic.Anthropic(api_key=self.anthropic_key)
                response = client.messages.create(
                    model="claude-sonnet-4-20250514",
                    max_tokens=2000,
                    messages=[{
                        "role": "user",
                        "content": f"Design a web app architecture for: {idea}. Include models, endpoints, pages."
                    }]
                )
                return {"llm_response": response.content[0].text, "idea": idea}
            except Exception:
                pass
        
        return {
            "models": [{"name": "Item", "fields": ["id", "name", "description", "created_at"]}],
            "endpoints": ["/api/items", "/api/items/{id}"],
            "pages": ["home", "list", "detail", "create"],
            "idea": idea
        }
    
    async def _generate_fastapi_app(self, app_name: str, architecture: Dict, idea: str) -> Dict[str, str]:
        """Generate FastAPI application files."""
        files = {}
        files["main.py"] = self.fastapi_manager.generate_main(app_name)
        files["models.py"] = self.fastapi_manager.generate_models(architecture.get("models", []))
        files["routes.py"] = self.fastapi_manager.generate_routes(architecture.get("endpoints", []))
        files["requirements.txt"] = "fastapi>=0.100.0\nuvicorn[standard]>=0.22.0\nsqlalchemy>=2.0.0\npydantic>=2.0.0\n"
        files["Dockerfile"] = f"FROM python:3.11-slim\nWORKDIR /app\nCOPY . .\nRUN pip install -r requirements.txt\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n"
        files["README.md"] = f"# {app_name}\n\n{idea}\n\nGenerated by LaunchForge\n"
        return files
    
    async def _generate_flask_app(self, app_name: str, architecture: Dict, idea: str) -> Dict[str, str]:
        """Generate Flask application files."""
        files = {}
        files["app.py"] = self.template_manager.generate_flask_app(app_name)
        files["models.py"] = self.template_manager.generate_models(architecture.get("models", []))
        files["requirements.txt"] = "flask>=2.3.0\nflask-sqlalchemy>=3.0.0\ngunicorn>=21.0.0\n"
        return files
