"""FastAPI project templates."""

def get_fastapi_main(project_name: str, has_auth: bool, has_db: bool, has_payments: bool) -> str:
    imports = ["from fastapi import FastAPI, HTTPException",
               "from fastapi.middleware.cors import CORSMiddleware"]
    
    if has_db:
        imports.append("from .database import engine, Base")
    if has_auth:
        imports.append("from .auth import router as auth_router")
    if has_payments:
        imports.append("from .payments import router as payments_router")
    
    imports_str = "\n".join(imports)
    
    routes = []
    if has_auth:
        routes.append("app.include_router(auth_router, prefix='/api/auth', tags=['auth'])")
    if has_payments:
        routes.append("app.include_router(payments_router, prefix='/api/payments', tags=['payments'])")
    
    routes_str = "\n    ".join(routes) if routes else "pass"
    
    db_init = """\n    # Create database tables\n    Base.metadata.create_all(bind=engine)""" if has_db else ""
    
    return f'''"""\n{project_name} - Generated by LaunchForge\n"""\n{imports_str}\nimport os\nfrom typing import Dict\n\napp = FastAPI(\n    title="{project_name}",\n    description="Generated by LaunchForge",\n    version="1.0.0"\n)\n\n# CORS\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=["*"],  # Configure for production\n    allow_credentials=True,\n    allow_methods=["*"],\n    allow_headers=["*"],\n){db_init}\n\n@app.on_event("startup")\nasync def startup_event():\n    """Run on application startup."""\n    {routes_str}\n\n@app.get("/")\nasync def root() -> Dict[str, str]:\n    return {{"message": "Welcome to {project_name}"}}\n\n@app.get("/health")\nasync def health() -> Dict[str, str]:\n    return {{"status": "healthy"}}\n\nif __name__ == "__main__":\n    import uvicorn\n    uvicorn.run(app, host="0.0.0.0", port=8000)\n'''


def get_fastapi_models(has_auth: bool, has_payments: bool) -> str:
    base_models = '''"""Database models."""\nfrom sqlalchemy import Column, Integer, String, DateTime, Boolean, Float\nfrom sqlalchemy.sql import func\nfrom .database import Base\n\n'''
    
    models = []
    
    if has_auth:
        models.append('''class User(Base):\n    __tablename__ = "users"\n    \n    id = Column(Integer, primary_key=True, index=True)\n    email = Column(String, unique=True, index=True)\n    hashed_password = Column(String)\n    is_active = Column(Boolean, default=True)\n    created_at = Column(DateTime(timezone=True), server_default=func.now())\n''')
    
    if has_payments:
        models.append('''class Subscription(Base):\n    __tablename__ = "subscriptions"\n    \n    id = Column(Integer, primary_key=True, index=True)\n    user_id = Column(Integer)\n    stripe_subscription_id = Column(String)\n    status = Column(String)  # active, canceled, past_due\n    plan = Column(String)\n    amount = Column(Float)\n    created_at = Column(DateTime(timezone=True), server_default=func.now())\n''')
    
    return base_models + "\n".join(models)

