from datetime import timezone
"""FastAPI project templates."""

def get_fastapi_main(project_name: str, has_auth: bool, has_db: bool, has_payments: bool) -> str:
    imports = ["from fastapi import FastAPI, HTTPException",
               "from fastapi.middleware.cors import CORSMiddleware"]
    
    if has_db:
        imports.append("from .database import engine, Base")
    if has_auth:
        imports.append("from .auth import router as auth_router")
    if has_payments:
        imports.append("from .payments import router as payments_router")
    
    imports_str = "\n".join(imports)
    
    routes = []
    if has_auth:
        routes.append("app.include_router(auth_router, prefix='/api/auth', tags=['auth'])")
    if has_payments:
        routes.append("app.include_router(payments_router, prefix='/api/payments', tags=['payments'])")
    
    routes_str = "\n    ".join(routes) if routes else "pass"
    
    db_init = """\n    # Create database tables\n    Base.metadata.create_all(bind=engine)""" if has_db else ""
    
    return f'''"""\n{project_name} - Generated by LaunchForge\n"""\n{imports_str}\nimport os\nfrom typing import Dict\n\napp = FastAPI(\n    title="{project_name}",\n    description="Generated by LaunchForge",\n    version="1.0.0"\n)\n\n# CORS\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=["*"],  # Configure for production\n    allow_credentials=True,\n    allow_methods=["*"],\n    allow_headers=["*"],\n){db_init}\n\n@app.on_event("startup")\nasync def startup_event():\n    """Run on application startup."""\n    {routes_str}\n\n@app.get("/")\nasync def root() -> Dict[str, str]:\n    return {{"message": "Welcome to {project_name}"}}\n\n@app.get("/health")\nasync def health() -> Dict[str, str]:\n    return {{"status": "healthy"}}\n\nif __name__ == "__main__":\n    import uvicorn\n    uvicorn.run(app, host="0.0.0.0", port=8000)\n'''


def get_fastapi_models(has_auth: bool, has_payments: bool) -> str:
    base_models = '''"""Database models."""\nfrom sqlalchemy import Column, Integer, String, DateTime, Boolean, Float\nfrom sqlalchemy.sql import func\nfrom .database import Base\n\n'''
    
    models = []
    
    if has_auth:
        models.append('''class User(Base):\n    __tablename__ = "users"\n    \n    id = Column(Integer, primary_key=True, index=True)\n    email = Column(String, unique=True, index=True)\n    hashed_password = Column(String)\n    is_active = Column(Boolean, default=True)\n    created_at = Column(DateTime(timezone=True), server_default=func.now())\n''')
    
    if has_payments:
        models.append('''class Subscription(Base):\n    __tablename__ = "subscriptions"\n    \n    id = Column(Integer, primary_key=True, index=True)\n    user_id = Column(Integer)\n    stripe_subscription_id = Column(String)\n    status = Column(String)  # active, canceled, past_due\n    plan = Column(String)\n    amount = Column(Float)\n    created_at = Column(DateTime(timezone=True), server_default=func.now())\n''')
    
    return base_models + "\n".join(models)


def get_fastapi_database() -> str:
    return '''"""Database configuration."""\nfrom sqlalchemy import create_engine\nfrom sqlalchemy.ext.declarative import declarative_base\nfrom sqlalchemy.orm import sessionmaker\nimport os\n\nDATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app.db")\n\nengine = create_engine(DATABASE_URL)\nSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)\nBase = declarative_base()\n\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()\n'''

def get_fastapi_auth() -> str:
    return '''"""Authentication routes."""\nfrom fastapi import APIRouter, Depends, HTTPException, status\nfrom fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm\nfrom sqlalchemy.orm import Session\nfrom passlib.context import CryptContext\nfrom jose import JWTError, jwt\nfrom datetime import datetime, timedelta\nfrom .database import get_db\nfrom .models import User\nimport os\n\nrouter = APIRouter()\npwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")\noauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")\n\nSECRET_KEY = os.getenv("SECRET_KEY", "change-me-in-production")\nALGORITHM = "HS256"\n\ndef verify_password(plain_password, hashed_password):\n    return pwd_context.verify(plain_password, hashed_password)\n\ndef get_password_hash(password):\n    return pwd_context.hash(password)\n\ndef create_access_token(data: dict):\n    to_encode = data.copy()\n    expire = datetime.now(timezone.utc) + timedelta(days=7)\n    to_encode.update({"exp": expire})\n    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)\n\n@router.post("/register")\nasync def register(email: str, password: str, db: Session = Depends(get_db)):\n    user = db.query(User).filter(User.email == email).first()\n    if user:\n        raise HTTPException(status_code=400, detail="Email already registered")\n    \n    hashed_password = get_password_hash(password)\n    user = User(email=email, hashed_password=hashed_password)\n    db.add(user)\n    db.commit()\n    db.refresh(user)\n    return {"id": user.id, "email": user.email}\n\n@router.post("/token")\nasync def login(form_data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):\n    user = db.query(User).filter(User.email == form_data.username).first()\n    if not user or not verify_password(form_data.password, user.hashed_password):\n        raise HTTPException(status_code=401, detail="Incorrect email or password")\n    \n    access_token = create_access_token(data={"sub": user.email})\n    return {"access_token": access_token, "token_type": "bearer"}\n'''

def get_fastapi_payments() -> str:
    return '''"""Stripe payment routes."""\nfrom fastapi import APIRouter, HTTPException, Depends\nfrom sqlalchemy.orm import Session\nimport stripe\nimport os\nfrom .database import get_db\nfrom .models import Subscription\n\nrouter = APIRouter()\nstripe.api_key = os.getenv("STRIPE_SECRET_KEY")\n\n@router.post("/create-checkout")\nasync def create_checkout_session(plan: str, user_id: int):\n    try:\n        prices = {\n            "basic": "price_basic",  # Replace with actual Stripe price IDs\n            "pro": "price_pro",\n            "enterprise": "price_enterprise"\n        }\n        \n        checkout_session = stripe.checkout.Session.create(\n            payment_method_types=["card"],\n            line_items=[{"price": prices.get(plan), "quantity": 1}],\n            mode="subscription",\n            success_url="https://yourapp.com/success",\n            cancel_url="https://yourapp.com/cancel",\n            metadata={"user_id": user_id}\n        )\n        return {"checkout_url": checkout_session.url}\n    except Exception as e:\n        raise HTTPException(status_code=400, detail=str(e))\n\n@router.post("/webhook")\nasync def webhook(request: Request, db: Session = Depends(get_db)):\n    # Handle Stripe webhooks\n    payload = await request.body()\n    sig_header = request.headers.get("stripe-signature")\n    \n    try:\n        event = stripe.Webhook.construct_event(\n            payload, sig_header, os.getenv("STRIPE_WEBHOOK_SECRET")\n        )\n    except ValueError:\n        raise HTTPException(status_code=400, detail="Invalid payload")\n    \n    # Handle the event\n    if event["type"] == "checkout.session.completed":\n        session = event["data"]["object"]\n        # Create subscription record\n        subscription = Subscription(\n            user_id=session["metadata"]["user_id"],\n            stripe_subscription_id=session["subscription"],\n            status="active"\n        )\n        db.add(subscription)\n        db.commit()\n    \n    return {"status": "success"}\n'''

def get_requirements_txt(has_auth: bool, has_db: bool, has_payments: bool, has_api: bool) -> str:
    reqs = ["fastapi>=0.104.0", "uvicorn[standard]>=0.24.0", "pydantic>=2.5.0"]\n    \n    if has_db:\n        reqs.extend(["sqlalchemy>=2.0.0", "alembic>=1.12.0"])\n    if has_auth:\n        reqs.extend(["python-jose[cryptography]>=3.3.0", "passlib[bcrypt]>=1.7.4", "python-multipart>=0.0.6"])\n    if has_payments:\n        reqs.append("stripe>=7.0.0")\n    if has_api:\n        reqs.append("httpx>=0.25.0")\n    \n    return "\\n".join(sorted(reqs))\n
def get_dockerfile() -> str:
    return '''FROM python:3.11-slim\n\nWORKDIR /app\n\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\nCOPY . .\n\nEXPOSE 8000\n\nCMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]\n'''

def get_env_template(has_db: bool, has_auth: bool, has_payments: bool) -> str:\n    env_vars = []\n    \n    if has_db:\n        env_vars.append("DATABASE_URL=postgresql://user:password@localhost:5432/dbname")\n    if has_auth:\n        env_vars.append("SECRET_KEY=your-secret-key-here-change-in-production")\n    if has_payments:\n        env_vars.extend(["STRIPE_SECRET_KEY=sk_test_xxx", "STRIPE_WEBHOOK_SECRET=whsec_xxx"])\n    \n    return "\\n".join(env_vars)\n
def get_readme(project_name: str, tech_stack: str) -> str:\n    return f'''# {project_name}\n\nGenerated by LaunchForge\n\n## Tech Stack\n- {tech_stack}\n- FastAPI\n- PostgreSQL (optional)\n- Stripe (optional)\n\n## Setup\n\n1. Install dependencies:\n```bash\npip install -r requirements.txt\n```\n\n2. Set up environment variables:\n```bash\ncp .env.example .env\n# Edit .env with your configuration\n```\n\n3. Run the application:\n```bash\nuvicorn main:app --reload\n```\n\n## API Docs\n\nOnce running, visit:\n- Swagger UI: http://localhost:8000/docs\n- ReDoc: http://localhost:8000/redoc\n\n## Deployment\n\nThis app is ready to deploy to:\n- Railway\n- Vercel\n- Heroku\n- Any Docker-compatible platform\n\n## License\n\nMIT\n'''
