"""FastAPI project templates."""


def get_fastapi_main(project_name: str, has_auth: bool, has_db: bool, has_payments: bool) -> str:
    imports = [
        "from fastapi import FastAPI, HTTPException",
        "from fastapi.middleware.cors import CORSMiddleware"
    ]

    if has_db:
        imports.append("from .database import engine, Base")
    if has_auth:
        imports.append("from .auth import router as auth_router")
    if has_payments:
        imports.append("from .payments import router as payments_router")

    imports_str = "\n".join(imports)

    routes = []
    if has_auth:
        routes.append("app.include_router(auth_router, prefix='/api/auth', tags=['auth'])")
    if has_payments:
        routes.append("app.include_router(payments_router, prefix='/api/payments', tags=['payments'])")

    routes_str = "\n    ".join(routes) if routes else "pass"

    db_init = """
    # Create database tables
    Base.metadata.create_all(bind=engine)""" if has_db else ""

    return f'''"""
{project_name} - Generated by LaunchForge
"""
{imports_str}
import os
from typing import Dict

app = FastAPI(
    title="{project_name}",
    description="Generated by LaunchForge",
    version="1.0.0"
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
){db_init}

@app.on_event("startup")
async def startup_event():
    """Run on application startup."""
    {routes_str}

@app.get("/")
async def root() -> Dict[str, str]:
    return {{"message": "Welcome to {project_name}"}}

@app.get("/health")
async def health() -> Dict[str, str]:
    return {{"status": "healthy"}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''


def get_fastapi_models(has_auth: bool, has_payments: bool) -> str:
    base_models = '''"""Database models."""
from sqlalchemy import Column, Integer, String, DateTime, Boolean, Float
from sqlalchemy.sql import func
from .database import Base

'''

    models = []

    if has_auth:
        models.append('''class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
''')

    if has_payments:
        models.append('''class Subscription(Base):
    __tablename__ = "subscriptions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer)
    stripe_subscription_id = Column(String)
    status = Column(String)
    plan = Column(String)
    amount = Column(Float)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
''')

    return base_models + "\n".join(models)


def get_fastapi_database() -> str:
    return '''"""Database configuration."""
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app.db")

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''


def get_fastapi_auth() -> str:
    return '''"""Authentication routes."""
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from sqlalchemy.orm import Session
from passlib.context import CryptContext
from jose import JWTError, jwt
from datetime import datetime, timedelta, timezone
from .database import get_db
from .models import User
import os

router = APIRouter()
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

SECRET_KEY = os.getenv("SECRET_KEY", "change-me-in-production")
ALGORITHM = "HS256"

def verify_password(plain_password, hashed_password):
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password):
    return pwd_context.hash(password)

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + timedelta(days=7)
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

@router.post("/register")
async def register(email: str, password: str, db: Session = Depends(get_db)):
    user = db.query(User).filter(User.email == email).first()
    if user:
        raise HTTPException(status_code=400, detail="Email already registered")

    hashed_password = get_password_hash(password)
    user = User(email=email, hashed_password=hashed_password)
    db.add(user)
    db.commit()
    db.refresh(user)
    return {"id": user.id, "email": user.email}

@router.post("/token")
async def login(form_data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    user = db.query(User).filter(User.email == form_data.username).first()
    if not user or not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(status_code=401, detail="Incorrect email or password")

    access_token = create_access_token(data={"sub": user.email})
    return {"access_token": access_token, "token_type": "bearer"}
'''


def get_fastapi_payments() -> str:
    return '''"""Stripe payment routes."""
from fastapi import APIRouter, HTTPException, Depends, Request
from sqlalchemy.orm import Session
import stripe
import os
from .database import get_db
from .models import Subscription

router = APIRouter()
stripe.api_key = os.getenv("STRIPE_SECRET_KEY")

@router.post("/create-checkout")
async def create_checkout_session(plan: str, user_id: int):
    try:
        prices = {
            "basic": "price_basic",
            "pro": "price_pro",
            "enterprise": "price_enterprise"
        }

        checkout_session = stripe.checkout.Session.create(
            payment_method_types=["card"],
            line_items=[{"price": prices.get(plan), "quantity": 1}],
            mode="subscription",
            success_url="https://yourapp.com/success",
            cancel_url="https://yourapp.com/cancel",
            metadata={"user_id": user_id}
        )
        return {"checkout_url": checkout_session.url}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@router.post("/webhook")
async def webhook(request: Request, db: Session = Depends(get_db)):
    payload = await request.body()
    sig_header = request.headers.get("stripe-signature")

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, os.getenv("STRIPE_WEBHOOK_SECRET")
        )
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid payload")

    if event["type"] == "checkout.session.completed":
        session = event["data"]["object"]
        subscription = Subscription(
            user_id=session["metadata"]["user_id"],
            stripe_subscription_id=session["subscription"],
            status="active"
        )
        db.add(subscription)
        db.commit()

    return {"status": "success"}
'''


def get_requirements_txt(has_auth: bool, has_db: bool, has_payments: bool, has_api: bool) -> str:
    reqs = ["fastapi>=0.104.0", "uvicorn[standard]>=0.24.0", "pydantic>=2.5.0"]

    if has_db:
        reqs.extend(["sqlalchemy>=2.0.0", "alembic>=1.12.0"])
    if has_auth:
        reqs.extend(["python-jose[cryptography]>=3.3.0", "passlib[bcrypt]>=1.7.4", "python-multipart>=0.0.6"])
    if has_payments:
        reqs.append("stripe>=7.0.0")
    if has_api:
        reqs.append("httpx>=0.25.0")

    return "\n".join(sorted(reqs))


def get_dockerfile() -> str:
    return '''FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''


def get_env_template(has_db: bool, has_auth: bool, has_payments: bool) -> str:
    env_vars = []

    if has_db:
        env_vars.append("DATABASE_URL=postgresql://user:password@localhost:5432/dbname")
    if has_auth:
        env_vars.append("SECRET_KEY=your-secret-key-here-change-in-production")
    if has_payments:
        env_vars.extend(["STRIPE_SECRET_KEY=sk_test_xxx", "STRIPE_WEBHOOK_SECRET=whsec_xxx"])

    return "\n".join(env_vars)


def get_readme(project_name: str, tech_stack: str) -> str:
    return f'''# {project_name}

Generated by LaunchForge

## Tech Stack
- {tech_stack}
- FastAPI
- PostgreSQL (optional)
- Stripe (optional)

## Setup

1. Install dependencies:
```bash
pip install -r requirements.txt
```

2. Set up environment variables:
```bash
cp .env.example .env
```

3. Run the application:
```bash
uvicorn main:app --reload
```

## API Docs

Once running, visit:
- Swagger UI: http://localhost:8000/docs
- ReDoc: http://localhost:8000/redoc

## License

MIT
'''
