// This file is auto-generated by the App-Builder Contract System
// It must match the backend Pydantic models.

export interface AutomationWorkflow {
  id: string;
  name: string;
  description?: string;
  trigger_type: string;
  trigger_condition: string;
  action_type: string;
  action_value: string;
  priority: number;
  is_active: boolean;
  last_execution_time?: string;
  created_at?: string;
}
