// This file is auto-generated by the App-Builder Contract System
// It must match the backend Pydantic models.

export interface Lead {
  id: string;
  lead_id: string;
  customer_name: string;
  email: string;
  phone: string;
  company?: string;
  source?: string;
  status?: string;
  notes?: string;
  last_contacted?: string;
  lead_score?: number;
  priority?: string;
  assigned_agent?: string;
  conversion_status?: boolean;
  conversion_date?: string;
  created_at?: string;
}
