// This file is auto-generated by the App-Builder Contract System
// It must match the backend Pydantic models.

export interface CustomerInteraction {
  id: string;
  customer_id: number;
  interaction_type: string;
  interaction_details?: string;
  interaction_date: string;
  assigned_agent_id: number;
  priority?: string;
  status: string;
  response_time?: number;
  last_updated?: string;
  created_at?: string;
}
