"""Initial LaunchForge schema

Revision ID: 40d31dbb95d6
Revises: 
Create Date: 2026-01-25 04:05:35.660795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40d31dbb95d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def get_json_type():
    """Return JSONB for PostgreSQL, JSON for others (SQLite, MySQL)."""
    from alembic import context
    if context.get_context().dialect.name == 'postgresql':
        return postgresql.JSONB(astext_type=Text())
    return sa.JSON()


def upgrade() -> None:
    """Upgrade schema."""
    json_type = get_json_type()
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(36), nullable=False),  # UUID as string for cross-DB compatibility
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_verified', 'users', ['email', 'email_verified'], unique=False)
    op.create_index('idx_users_subscription', 'users', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    op.create_table('projects',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('user_id', sa.String(36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'GENERATED', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('code_url', sa.String(length=500), nullable=True),
    sa.Column('deployment_url', sa.String(length=500), nullable=True),
    sa.Column('config', json_type, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_name', 'projects', ['name'], unique=False)
    op.create_index('idx_projects_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    
    op.create_table('deployments',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'ROLLED_BACK', name='deploymentstatus'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('logs', json_type, nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', json_type, nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('build_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deployments_deployed_at', 'deployments', ['deployed_at'], unique=False)
    op.create_index('idx_deployments_project_status', 'deployments', ['project_id', 'status'], unique=False)
    op.create_index('idx_deployments_provider', 'deployments', ['provider'], unique=False)
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    
    op.create_table('generations',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('market_intel', json_type, nullable=True),
    sa.Column('generated_code', json_type, nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generations_model', 'generations', ['model_used'], unique=False)
    op.create_index('idx_generations_project_created', 'generations', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_generations_project_id'), 'generations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_project_id'), table_name='generations')
    op.drop_index('idx_generations_project_created', table_name='generations')
    op.drop_index('idx_generations_model', table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_index('idx_deployments_provider', table_name='deployments')
    op.drop_index('idx_deployments_project_status', table_name='deployments')
    op.drop_index('idx_deployments_deployed_at', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index('idx_projects_user_status', table_name='projects')
    op.drop_index('idx_projects_name', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_subscription', table_name='users')
    op.drop_index('idx_users_email_verified', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
