"""Add authentication fields to users

Revision ID: ef2c9ca2bc1b
Revises: 40d31dbb95d6
Create Date: 2026-01-25 04:24:25.131247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2c9ca2bc1b'
down_revision: Union[str, Sequence[str], None] = '40d31dbb95d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_projects_not_deleted', 'projects', ['is_deleted'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    op.create_index('idx_users_not_deleted', 'users', ['is_deleted'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_not_deleted', table_name='users', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'name')
    op.drop_index('idx_projects_not_deleted', table_name='projects', postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###
