// This file is auto-generated by the App-Builder Contract System
// It must match the backend Pydantic models.

export interface Customer {
  id: string;
  email: string;
  first_name?: string;
  last_name?: string;
  company?: string;
  phone?: string;
  website?: string;
  industry?: string;
  customer_segment?: string;
  last_contact_date?: string;
  lead_score?: number;
  preferred_contact_method?: string;
  notes?: string;
  account_manager?: string;
  ai_analysis_status?: string;
  last_ai_update?: string;
  customer_lifetime_value?: number;
  created_at?: string;
}
