// This file is auto-generated by the App-Builder Contract System
// It must match the backend Pydantic models.

export interface Automation {
  id: string;
  name: string;
  description?: string;
  workflow_type: string;
  trigger_condition?: string;
  action_steps?: string;
  status: string;
  last_run_time?: string;
  next_run_time?: string;
  is_active: boolean;
  assignee_id?: number;
  customer_segment?: string;
  created_at?: string;
}
