"""
Code Generation Engine v2 for Ignara.

KEY DIFFERENCE from v1: Every file is generated by the LLM with full context
about the system architecture. No static template substitution.

Architecture:
1. Takes a SystemSpec from the Architect
2. Plans the file tree
3. Generates each file with LLM, providing context about:
   - The full system spec
   - Related entities and their schemas
   - What other files exist and their interfaces
4. Validates each generated file (AST check for Python, basic syntax for TS/JS)
5. Self-heals broken files with LLM retry
6. Produces a complete, downloadable project

File Generation Strategy:
- Backend files generated in dependency order: models → schemas → CRUD → routes → main
- Frontend files: types → components → pages → layout → config
- Config files: Docker, CI/CD, env, etc.
"""
from __future__ import annotations

import ast
import asyncio
import logging
import os
import secrets
import textwrap
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, AsyncGenerator, Dict, List, Optional

from pydantic import BaseModel, Field

from src.code_generation.architect import (
    EntitySpec,
    IntegrationSpec,
    PageSpec,
    RelationshipSpec,
    RoleSpec,
    RouteSpec,
    SystemSpec,
    TechStackSpec,
)
from src.llm import get_llm_client
from src.llm.client import BaseLLMClient

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# System prompt constant — used for every LLM call in this module
# ---------------------------------------------------------------------------

CODEGEN_SYSTEM_PROMPT = """You are an expert software engineer and code generator for Ignara,
an AI-powered application builder. Your job is to generate production-ready source code files.

Rules you MUST follow:
1. Output ONLY the raw source code — no markdown fences, no explanation, no commentary.
2. Every file must be complete and self-contained; never use placeholder comments like
   "# TODO: implement" or "// add logic here". Write the full implementation.
3. Follow modern best practices for the relevant language/framework.
4. Honour ALL business rules and entity relationships described in the spec.
5. Use proper type annotations throughout (Python type hints, TypeScript types).
6. Handle errors gracefully with appropriate HTTP status codes and user-facing messages.
7. Never hard-code secrets. Use environment variables accessed through a config module.
8. Generate idiomatic, readable code with clear docstrings and inline comments where helpful.
"""


# ---------------------------------------------------------------------------
# Result models
# ---------------------------------------------------------------------------


class FileCategory(str, Enum):
    BACKEND_MODEL = "backend_model"
    BACKEND_SCHEMA = "backend_schema"
    BACKEND_CRUD = "backend_crud"
    BACKEND_ROUTE = "backend_route"
    BACKEND_CORE = "backend_core"
    BACKEND_DB = "backend_db"
    BACKEND_TEST = "backend_test"
    BACKEND_CONFIG = "backend_config"
    FRONTEND_TYPE = "frontend_type"
    FRONTEND_API = "frontend_api"
    FRONTEND_COMPONENT = "frontend_component"
    FRONTEND_PAGE = "frontend_page"
    FRONTEND_CONFIG = "frontend_config"
    INFRASTRUCTURE = "infrastructure"


class GeneratedFile(BaseModel):
    """Metadata about a single generated file."""

    path: str
    lines: int = 0
    category: FileCategory = FileCategory.BACKEND_CONFIG
    llm_generated: bool = True
    heal_attempts: int = 0


class GenerationResult(BaseModel):
    """Result of a complete codebase generation run."""

    output_path: str
    files: List[GeneratedFile] = Field(default_factory=list)
    total_files: int = 0
    total_lines: int = 0
    backend_files: int = 0
    frontend_files: int = 0
    generation_time_seconds: float = 0.0
    llm_calls_made: int = 0
    warnings: List[str] = Field(default_factory=list)


class ProgressEvent(BaseModel):
    """Emitted during generation to report progress to callers."""

    step: str
    percentage: float
    current_file: Optional[str] = None
    message: str = ""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


@dataclass
class _FileSpec:
    """Internal plan record for a file that needs to be generated."""

    relative_path: str
    category: FileCategory
    prompt_builder: Any  # callable(context) -> str  — built later
    description: str = ""
    # Dependencies: list of relative paths that must be generated first.
    # Files with no deps (or whose deps are satisfied) can run concurrently.
    depends_on: List[str] = field(default_factory=list)


@dataclass
class _GenerationContext:
    """Mutable context threaded through the generation pipeline."""

    spec: SystemSpec
    output_dir: Path
    theme: str
    secret_key: str = field(default_factory=lambda: secrets.token_urlsafe(32))
    # Accumulates a summary of already-generated files' key exports/interfaces
    generated_interfaces: Dict[str, str] = field(default_factory=dict)
    llm_calls: int = 0
    warnings: List[str] = field(default_factory=list)
    # Pre-computed spec summary (computed once, shared across all prompts)
    _spec_summary_cache: Optional[str] = None
    # Lock for thread-safe updates to shared state
    _lock: asyncio.Lock = field(default_factory=asyncio.Lock)


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------


def _validate_python(source: str) -> Optional[str]:
    """
    Attempt to parse *source* as Python.

    Returns ``None`` on success, or an error message string on failure.
    """
    try:
        ast.parse(source)
        return None
    except SyntaxError as exc:
        return f"SyntaxError at line {exc.lineno}: {exc.msg}"


def _validate_typescript(source: str) -> Optional[str]:
    """
    Perform lightweight heuristic checks on TypeScript/JavaScript source.

    Returns ``None`` when the source looks plausible, or an error message.
    """
    stripped = source.strip()
    if not stripped:
        return "File is empty"

    # Balanced braces check (handles basic structural issues)
    depth = 0
    in_string: Optional[str] = None
    prev = ""
    for ch in stripped:
        if in_string:
            if ch == in_string and prev != "\\":
                in_string = None
        else:
            if ch in ('"', "'", "`"):
                in_string = ch
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth < 0:
                    return "Unmatched closing brace '}'"
        prev = ch

    if depth != 0:
        return f"Unbalanced braces: {depth} unclosed '{'{'}'"

    # Must contain at least one meaningful construct
    keywords = (
        "export", "import", "const", "let", "function",
        "class", "interface", "type ", "return",
    )
    if not any(kw in stripped for kw in keywords):
        return "File appears to contain no meaningful TypeScript/JavaScript constructs"

    return None


def _validate_file(relative_path: str, source: str) -> Optional[str]:
    """Dispatch to the correct validator based on file extension."""
    ext = Path(relative_path).suffix.lower()
    if ext == ".py":
        return _validate_python(source)
    if ext in (".ts", ".tsx", ".js", ".jsx"):
        return _validate_typescript(source)
    return None  # No validation for JSON, TOML, YAML, Dockerfile, etc.


# ---------------------------------------------------------------------------
# Prompt building utilities
# ---------------------------------------------------------------------------


def _spec_summary(spec: SystemSpec, *, compact: bool = False) -> str:
    """Render a concise text representation of *spec* for use in prompts.

    Args:
        spec: The system specification.
        compact: If True, omit API routes and business rules for shorter prompts
                 (useful for config/infra files that don't need route details).
    """
    lines: List[str] = [
        f"App: {spec.app_name}",
        f"Description: {spec.description}",
        "",
        "Entities:",
    ]
    for ent in spec.entities:
        field_list = ", ".join(
            f"{f.name}: {f.type}{'(required)' if f.required else '(optional)'}"
            for f in ent.fields
        )
        rel_list = ", ".join(
            f"{r.type} → {r.entity}" for r in ent.relationships
        )
        lines.append(f"  • {ent.name} [{ent.table_name if hasattr(ent, 'table_name') else ent.plural}]")
        if field_list:
            lines.append(f"      Fields: {field_list}")
        if rel_list:
            lines.append(f"      Relations: {rel_list}")

    if not compact:
        lines += ["", "API Routes:"]
        for route in spec.api_routes[:20]:  # cap at 20 to keep prompt size sane
            lines.append(f"  {route.method:6} {route.path}  ({'auth' if route.auth_required else 'public'})")
            if route.business_logic:
                lines.append(f"         Logic: {route.business_logic[:120]}")

    lines += ["", "Roles: " + ", ".join(r.name for r in spec.roles)]

    lines += ["", "Integrations: " + ", ".join(i.name for i in spec.integrations)]

    if not compact:
        lines += ["", "Business Rules:"]
        for rule in spec.business_rules:
            lines.append(f"  • {rule}")

    lines += [
        "",
        f"Tech Stack: {spec.tech_stack.backend_framework} / "
        f"{spec.tech_stack.frontend_framework} / {spec.tech_stack.database}",
    ]
    return "\n".join(lines)


def _interfaces_summary(ctx: _GenerationContext, *, relevant_to: Optional[str] = None) -> str:
    """Render already-generated file interfaces for inclusion in subsequent prompts.

    Args:
        ctx: Generation context containing all generated interfaces so far.
        relevant_to: If provided, only include interfaces that are likely
                     relevant to the file at this path (same entity, same
                     layer, or direct dependency).
    """
    if not ctx.generated_interfaces:
        return "(No files generated yet.)"

    items = list(ctx.generated_interfaces.items())

    # If we know what file we're generating, filter to relevant interfaces only
    if relevant_to:
        # Extract the entity name and layer from the target path
        target_lower = relevant_to.lower()
        # e.g. "backend/app/crud/user.py" → entity hint = "user"
        target_stem = Path(relevant_to).stem.lower()
        # e.g. "backend/app/crud/" → layer hint = "crud"
        target_parts = set(Path(relevant_to).parts)

        def _relevance(path: str) -> int:
            """Score how relevant *path* is to the target file (higher = more relevant)."""
            score = 0
            path_lower = path.lower()
            path_stem = Path(path).stem.lower()
            # Same entity name in filename → very relevant
            if target_stem and target_stem != "__init__" and target_stem in path_lower:
                score += 10
            # Same directory layer (models referencing db, schemas referencing models, etc.)
            if any(p in path_lower for p in target_parts if p not in {"backend", "frontend", "app", "src"}):
                score += 3
            # Core / DB files are always somewhat relevant to backend files
            if "backend" in target_lower and ("core/" in path_lower or "db/" in path_lower):
                score += 5
            # Types and API client are always relevant to frontend files
            if "frontend" in target_lower and ("types/" in path_lower or "lib/api" in path_lower):
                score += 5
            return score

        # Sort by relevance, take top 15 most relevant
        scored = [(path, iface, _relevance(path)) for path, iface in items]
        scored.sort(key=lambda x: x[2], reverse=True)
        items = [(p, i) for p, i, s in scored if s > 0][:15]

        if not items:
            # Fallback: just show the last 10
            items = list(ctx.generated_interfaces.items())[-10:]
    else:
        items = items[-30:]  # cap at 30

    parts = []
    for path, iface in items:
        parts.append(f"--- {path} ---\n{iface}\n")
    return "\n".join(parts)


def _entity_detail(entity: EntitySpec) -> str:
    """Render detailed information about a single entity."""
    lines = [f"Entity: {entity.name}"]
    if entity.description:
        lines.append(f"Description: {entity.description}")
    lines.append("Fields:")
    for f in entity.fields:
        req = "required" if f.required else "optional"
        default = f" (default: {f.default})" if f.default else ""
        lines.append(f"  - {f.name}: {f.type} [{req}]{default}")
        if f.validation_rules:
            lines.append(f"    Validation: {', '.join(f.validation_rules)}")
    if entity.relationships:
        lines.append("Relationships:")
        for r in entity.relationships:
            lines.append(f"  - {r.type} → {r.entity}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Prompt factories for each file category
# ---------------------------------------------------------------------------


def _build_model_prompt(entity: EntitySpec, ctx: _GenerationContext) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate a complete SQLAlchemy ORM model file for the entity described below.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ENTITY DETAIL ===
        {_entity_detail(entity)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/models/{entity.name.lower()}.py
        - Use SQLAlchemy 2.x declarative_base (imported from backend/app/db/base.py as Base).
        - Add all fields with appropriate Column types:
            string → String(255), text → Text, integer → Integer,
            decimal → Float, boolean → Boolean, timestamp → DateTime,
            uuid → String(36) with server_default=func.uuid_generate_v4() where supported.
        - Add created_at and updated_at DateTime columns with server defaults if entity.timestamps is True.
        - Add deleted_at DateTime column (nullable) for soft-delete if entity.soft_delete is True.
        - Implement all relationships using SQLAlchemy relationship() with appropriate back_populates.
        - Add __tablename__ class variable.
        - Add __repr__ returning a useful string.
        - Import everything from sqlalchemy; do NOT import from future models.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_schema_prompt(entity: EntitySpec, ctx: _GenerationContext) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate complete Pydantic v2 schema classes for the entity described below.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ENTITY DETAIL ===
        {_entity_detail(entity)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/schemas/{entity.name.lower()}.py
        - Create four Pydantic BaseModel subclasses:
            1. {entity.name}Base — shared fields (exclude id, created_at, updated_at)
            2. {entity.name}Create(Base) — fields required for creation
            3. {entity.name}Update(Base) — all fields Optional for partial update
            4. {entity.name}Read(Base) — full read schema including id, timestamps, relationships as nested schemas
        - Use Optional[T] for nullable fields, proper validators where applicable.
        - Add model_config = ConfigDict(from_attributes=True) for ORM compatibility.
        - Include field descriptions in Field(..., description="...").
        - Add an example schema in model_config = ConfigDict(json_schema_extra={{"example": {{...}}}}).
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_crud_prompt(entity: EntitySpec, ctx: _GenerationContext) -> str:
    spec = ctx.spec
    routes_for_entity = [
        r for r in spec.api_routes
        if entity.name.lower() in r.path.lower() or entity.name.lower() in (r.tags or [entity.name.lower()])
    ]
    route_info = "\n".join(
        f"  {r.method} {r.path}: {r.business_logic[:200]}" for r in routes_for_entity
    ) or "  (standard CRUD)"

    return textwrap.dedent(f"""
        Generate a complete CRUD operations module for the entity described below.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ENTITY DETAIL ===
        {_entity_detail(entity)}

        === BUSINESS LOGIC FOR THIS ENTITY ===
        {route_info}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/crud/{entity.name.lower()}.py
        - Import the SQLAlchemy model from backend/app/models/{entity.name.lower()}.py
        - Import the Pydantic schemas from backend/app/schemas/{entity.name.lower()}.py
        - Use SQLAlchemy async session: from sqlalchemy.ext.asyncio import AsyncSession
        - Implement these async functions:
            get_{entity.name.lower()}(db, id) → Optional[model]
            get_{entity.plural.lower() if hasattr(entity, 'plural') else entity.name.lower()+'s'}(db, skip, limit, **filters) → List[model]
            create_{entity.name.lower()}(db, obj_in: Create) → model
            update_{entity.name.lower()}(db, db_obj: model, obj_in: Update) → model
            delete_{entity.name.lower()}(db, id) → bool  (soft-delete if applicable)
        - Enforce all business rules for this entity listed in the spec.
        - Use select(), where(), offset(), limit() from sqlalchemy.future.
        - Commit and refresh after create/update.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_route_prompt(entity: EntitySpec, ctx: _GenerationContext) -> str:
    spec = ctx.spec
    routes_for_entity = [
        r for r in spec.api_routes
        if entity.name.lower() in r.path.lower()
    ]
    route_descriptions = "\n".join(
        f"  {r.method} {r.path}  (auth={r.auth_required}): {r.business_logic[:200]}"
        for r in routes_for_entity
    ) or "  (standard REST CRUD endpoints)"

    roles_info = "\n".join(f"  {r.name}: {', '.join(r.permissions)}" for r in spec.roles)

    return textwrap.dedent(f"""
        Generate a complete FastAPI router for the entity described below.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ENTITY DETAIL ===
        {_entity_detail(entity)}

        === ROUTES TO IMPLEMENT ===
        {route_descriptions}

        === ROLES AND PERMISSIONS ===
        {roles_info}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/api/endpoints/{entity.name.lower()}.py
        - Use APIRouter with prefix="/{entity.plural.lower() if hasattr(entity, 'plural') else entity.name.lower()+'s'}" and tags=["{entity.name}"]
        - Import CRUD functions from backend/app/crud/{entity.name.lower()}.py
        - Import schemas from backend/app/schemas/{entity.name.lower()}.py
        - Use AsyncSession dependency: db: AsyncSession = Depends(get_db)
        - Use current_user dependency for auth-required endpoints: current_user = Depends(get_current_user)
        - Return proper HTTP status codes (201 for create, 404 for not found, 400 for bad request).
        - Handle not-found cases and raise HTTPException(status_code=404) appropriately.
        - Use response_model= annotations on every route.
        - Include pagination params (skip: int = 0, limit: int = 100) on list endpoints.
        - Apply role-based access checks from the permissions spec where relevant.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_main_router_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    entity_names = [e.name.lower() for e in spec.entities]
    return textwrap.dedent(f"""
        Generate the main FastAPI API router that aggregates all entity routers.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ENTITY ROUTERS TO INCLUDE ===
        {chr(10).join('  - backend/app/api/endpoints/' + n + '.py' for n in entity_names)}
        Also include: backend/app/api/endpoints/auth.py

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/api/__init__.py
        - Create an api_router = APIRouter()
        - Include each entity router with: api_router.include_router(...)
        - Include the auth router at prefix="/auth"
        - Export api_router
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_main_app_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    integrations = [i.name for i in spec.integrations]
    return textwrap.dedent(f"""
        Generate the main FastAPI application entry point.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === INTEGRATIONS ===
        {', '.join(integrations) if integrations else 'None'}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/main.py
        - Create app = FastAPI(title="{spec.app_name}", version="1.0.0", description="{spec.description[:200]}")
        - Add CORSMiddleware allowing the frontend origin (from settings.ALLOWED_ORIGINS).
        - Add GZipMiddleware.
        - Include the api_router from backend/app/api/__init__.py with prefix="/api/v1"
        - Add a health check endpoint GET /health that returns {{"status": "ok"}}.
        - Add startup/shutdown event handlers to init/close the DB connection pool.
        - Configure structured logging using Python logging.
        - Do not hard-code any secrets; use settings from backend/app/core/config.py.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_core_config_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    env_vars = []
    for integration in spec.integrations:
        env_vars.extend(integration.env_vars)
    extra_env = "\n".join(f"  {v}" for v in env_vars) or "  (none)"

    return textwrap.dedent(f"""
        Generate the settings/configuration module for the FastAPI backend.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === REQUIRED ENV VARS FROM INTEGRATIONS ===
        {extra_env}

        === REQUIREMENTS ===
        - File: backend/app/core/config.py
        - Use pydantic-settings BaseSettings with model_config = SettingsConfigDict(env_file=".env")
        - Include these settings:
            PROJECT_NAME: str = "{spec.app_name}"
            VERSION: str = "1.0.0"
            API_V1_STR: str = "/api/v1"
            SECRET_KEY: str = "{ctx.secret_key}"  (document that this MUST be overridden in production)
            ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
            REFRESH_TOKEN_EXPIRE_DAYS: int = 7
            ALGORITHM: str = "HS256"
            DATABASE_URL: str  (no default — must be set in environment)
            REDIS_URL: str = "redis://localhost:6379/0"
            ALLOWED_ORIGINS: list[str] = ["http://localhost:3000"]
            DEBUG: bool = False
            ENVIRONMENT: str = "development"
        - Include a setting for each integration env var collected above.
        - Export a single `settings = Settings()` instance.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_core_security_prompt(ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate the security utilities module (password hashing and JWT tokens) for a FastAPI app.

        === SYSTEM SPEC ===
        {_spec_summary(ctx.spec)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/core/security.py
        - Use passlib[bcrypt] for password hashing:
            hash_password(password: str) -> str
            verify_password(plain: str, hashed: str) -> bool
        - Use python-jose for JWT:
            create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str
            create_refresh_token(data: dict) -> str
            decode_token(token: str) -> dict  (raises HTTPException on invalid/expired)
        - Import SECRET_KEY and ALGORITHM from backend/app/core/config.py settings.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_core_auth_prompt(ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate FastAPI dependency functions for authentication and authorisation.

        === SYSTEM SPEC ===
        {_spec_summary(ctx.spec)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/core/auth.py
        - Implement:
            get_db() → async generator yielding AsyncSession
            get_current_user(token: str = Depends(oauth2_scheme), db = Depends(get_db)) → User model
            get_current_active_user(current_user = Depends(get_current_user)) → User model
            require_role(*roles: str) → Depends-compatible factory that raises 403 if role not met
        - Use OAuth2PasswordBearer(tokenUrl="/api/v1/auth/login")
        - Decode the JWT using decode_token from backend/app/core/security.py
        - Fetch the user from the DB using the subject claim.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_db_session_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate the SQLAlchemy async database session setup for the FastAPI backend.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === REQUIREMENTS ===
        - File: backend/app/db/session.py
        - Use sqlalchemy.ext.asyncio: create_async_engine, AsyncSession, async_sessionmaker
        - Read DATABASE_URL from settings (backend/app/core/config.py).
        - Create engine with pool_pre_ping=True, pool_size=10, max_overflow=20.
        - Create AsyncSessionLocal = async_sessionmaker(...)
        - Export: engine, AsyncSessionLocal
        - Also export async get_db() generator that yields a session and commits/rolls back on exit.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_db_base_prompt(ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate the SQLAlchemy declarative base and a shared BaseModel mixin.

        === REQUIREMENTS ===
        - File: backend/app/db/base.py
        - Create Base = DeclarativeBase() using SQLAlchemy 2.x style.
        - Create a TimestampMixin class with created_at and updated_at columns.
        - Import all ORM models at the bottom of the file so Alembic autogenerate picks them up.
          Models to import: {', '.join(e.name.lower() for e in ctx.spec.entities)}.
        - Export Base, TimestampMixin.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_auth_router_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate the FastAPI authentication router (login, register, refresh, logout).

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/app/api/endpoints/auth.py
        - Endpoints:
            POST /login  — OAuth2PasswordRequestForm, return access + refresh tokens
            POST /register — create new user, return access token
            POST /refresh  — take refresh token, return new access token
            POST /logout   — invalidate session/token (or just return success)
            GET  /me       — return current user profile
        - Use schemas from backend/app/schemas/user.py (or equivalent User entity).
        - Use CRUD functions for the User entity.
        - Hash passwords before storage; verify on login.
        - Return OAuth2-compatible token response: {{"access_token": ..., "token_type": "bearer"}}
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_test_prompt(entity: EntitySpec, ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate pytest tests for the {entity.name} entity API endpoints.

        === SYSTEM SPEC ===
        {_spec_summary(ctx.spec)}

        === ENTITY DETAIL ===
        {_entity_detail(entity)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: backend/tests/test_{entity.name.lower()}.py
        - Use pytest with pytest-asyncio for async tests.
        - Use httpx.AsyncClient as the test client.
        - Test at minimum:
            test_create_{entity.name.lower()} — POST creates successfully
            test_read_{entity.name.lower()} — GET by ID returns correct data
            test_list_{entity.plural.lower() if hasattr(entity, 'plural') else entity.name.lower()+'s'} — GET list returns paginated results
            test_update_{entity.name.lower()} — PATCH updates fields
            test_delete_{entity.name.lower()} — DELETE removes/soft-deletes
            test_unauthorized_{entity.name.lower()} — unauthenticated access returns 401
        - Use fixtures for test DB session and authenticated test client.
        - Output ONLY the Python source — no markdown, no explanation.
    """).strip()


def _build_requirements_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    integration_deps = []
    for i in spec.integrations:
        name_lower = i.name.lower()
        if "stripe" in name_lower:
            integration_deps.append("stripe>=7.0.0")
        elif "sendgrid" in name_lower:
            integration_deps.append("sendgrid>=6.11.0")
        elif "twilio" in name_lower:
            integration_deps.append("twilio>=8.0.0")
        elif "s3" in name_lower or "aws" in name_lower:
            integration_deps.append("boto3>=1.34.0")
        elif "firebase" in name_lower:
            integration_deps.append("firebase-admin>=6.0.0")
        elif "openai" in name_lower:
            integration_deps.append("openai>=1.0.0")
        elif "redis" in name_lower:
            integration_deps.append("redis>=5.0.0")

    extra = "\n".join(integration_deps)
    return textwrap.dedent(f"""
        Generate a requirements.txt for a FastAPI backend project.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === EXTRA DEPENDENCIES NEEDED FOR INTEGRATIONS ===
        {extra or '(none beyond core)'}

        === REQUIREMENTS ===
        - File: backend/requirements.txt
        - Always include:
            fastapi>=0.110.0
            uvicorn[standard]>=0.29.0
            sqlalchemy>=2.0.0
            asyncpg>=0.29.0
            alembic>=1.13.0
            pydantic>=2.6.0
            pydantic-settings>=2.2.0
            python-jose[cryptography]>=3.3.0
            passlib[bcrypt]>=1.7.4
            python-multipart>=0.0.9
            httpx>=0.27.0
            redis>=5.0.0
            pytest>=8.0.0
            pytest-asyncio>=0.23.0
        - Add the integration-specific deps listed above.
        - Pin to minor versions using >=X.Y.0 style (not exact pins).
        - Output ONLY the requirements.txt content — no markdown, no explanation.
    """).strip()


def _build_backend_dockerfile_prompt(ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate a production-ready Dockerfile for the FastAPI backend.

        === REQUIREMENTS ===
        - File: backend/Dockerfile
        - Use python:3.11-slim as base image.
        - Multi-stage build: builder stage installs deps, final stage is lean.
        - Run as non-root user (uid 1000).
        - Copy requirements.txt, install with pip --no-cache-dir.
        - Copy application code.
        - Expose port 8000.
        - Use CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        - Output ONLY the Dockerfile content — no markdown, no explanation.
    """).strip()


def _build_alembic_ini_prompt(ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate an alembic.ini configuration file for database migrations.

        === REQUIREMENTS ===
        - File: backend/alembic.ini
        - Set script_location = alembic
        - Set sqlalchemy.url placeholder as driver://user:pass@host/dbname (will be overridden by env)
        - Set file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s
        - Configure logging section with alembic and sqlalchemy.engine loggers.
        - Output ONLY the alembic.ini content — no markdown, no explanation.
    """).strip()


# ---------------------------------------------------------------------------
# Frontend prompt builders
# ---------------------------------------------------------------------------


def _build_frontend_types_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate TypeScript interface definitions that mirror the backend Pydantic schemas.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: frontend/src/types/index.ts
        - Export a TypeScript interface for each entity Read schema.
        - Export create/update payload types (Omit id, timestamps).
        - Export a generic ApiResponse<T> type: {{ data: T; message: string; success: boolean }}
        - Export a PaginatedResponse<T> type: {{ items: T[]; total: number; page: number; per_page: number }}
        - Use proper TypeScript types: string, number, boolean, Date (as string for JSON), optional fields with ?
        - Output ONLY the TypeScript source — no markdown, no explanation.
    """).strip()


def _build_api_client_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    entity_names = [e.name for e in spec.entities]
    return textwrap.dedent(f"""
        Generate a fully-typed TypeScript API client for the frontend.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ENTITIES ===
        {', '.join(entity_names)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: frontend/src/lib/api.ts
        - Use fetch() with a base URL from process.env.NEXT_PUBLIC_API_URL
        - Add an Authorization header using a token stored in localStorage.
        - Implement a generic request<T>(method, path, body?) → Promise<T> helper.
        - For each entity, export a typed API object with methods:
            list(params?: {{ skip?: number; limit?: number }}) → Promise<PaginatedResponse<EntityRead>>
            get(id: string) → Promise<EntityRead>
            create(data: EntityCreate) → Promise<EntityRead>
            update(id: string, data: EntityUpdate) → Promise<EntityRead>
            remove(id: string) → Promise<void>
        - Export authApi with: login(), register(), logout(), getMe(), refreshToken()
        - Handle HTTP errors by throwing typed ApiError objects.
        - Output ONLY the TypeScript source — no markdown, no explanation.
    """).strip()


def _build_ui_components_prompt(ctx: _GenerationContext, theme: str) -> str:
    return textwrap.dedent(f"""
        Generate a set of reusable React UI components styled with Tailwind CSS.

        === THEME ===
        {theme}

        === REQUIREMENTS ===
        - File: frontend/src/components/ui/index.tsx
        - Export these components:
            Button — variants: primary, secondary, destructive, ghost; sizes: sm, md, lg
            Input — with label, error, hint props
            Card — with header, content, footer slots
            Badge — with variants: default, success, warning, error
            Modal — controlled with isOpen/onClose; renders a backdrop and panel
            Spinner — loading indicator
            Table — with columns definition and data array props, including pagination controls
            Alert — variants: info, success, warning, error with dismissible prop
            Avatar — with src, name initials fallback
            Dropdown — with trigger and items
        - Use "use client" directive at the top.
        - Use Tailwind utility classes; respect the {theme} visual theme.
        - Keep components fully typed with TypeScript.
        - Output ONLY the TypeScript/TSX source — no markdown, no explanation.
    """).strip()


def _build_entity_component_prompt(entity: EntitySpec, ctx: _GenerationContext, theme: str) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate React components for managing the {entity.name} entity in the frontend.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === ENTITY DETAIL ===
        {_entity_detail(entity)}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: frontend/src/components/{entity.name.lower()}/{entity.name}Components.tsx
        - Export three components:
            {entity.name}Table — renders a list of {entity.plural.lower() if hasattr(entity, 'plural') else entity.name.lower()+'s'} with columns for key fields, row actions (edit, delete)
            {entity.name}Form — create/edit form with controlled inputs, Zod validation, submission handler
            {entity.name}Card — summary card showing key fields, used in dashboard widgets
        - Use "use client" directive.
        - Import shared UI components from @/components/ui.
        - Import API methods from @/lib/api.
        - Import types from @/types.
        - Use React Hook Form + Zod for form validation.
        - Apply {theme} visual theme via Tailwind classes.
        - Output ONLY the TypeScript/TSX source — no markdown, no explanation.
    """).strip()


def _build_page_prompt(page: PageSpec, ctx: _GenerationContext, theme: str) -> str:
    spec = ctx.spec
    safe_route = page.route.strip("/").replace("/", "_") or "home"
    related_entities = "\n".join(
        _entity_detail(e)
        for e in spec.entities
        if e.name.lower() in [r.lower() for r in getattr(page, "related_entities", [])]
    )
    return textwrap.dedent(f"""
        Generate a Next.js 14 App Router page for the page described below.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === PAGE SPEC ===
        Route: {page.route}
        Title: {page.title}
        Description: {getattr(page, 'description', '')}
        Layout: {page.layout_type}
        Auth Required: {page.auth_required}
        Components: {', '.join(c.name for c in page.components)}

        === RELATED ENTITIES ===
        {related_entities or '(none)'}

        === ALREADY GENERATED INTERFACES ===
        {_interfaces_summary(ctx)}

        === REQUIREMENTS ===
        - File: frontend/src/app/{safe_route}/page.tsx
        - Use Next.js App Router conventions (async server component unless interactivity needed).
        - If auth_required, check session and redirect to /login if not authenticated.
        - Import and use the relevant entity components and UI components.
        - Display page title in an <h1> with proper Tailwind styling for {theme} theme.
        - Include loading and error states.
        - Use generateMetadata() for SEO.
        - Output ONLY the TypeScript/TSX source — no markdown, no explanation.
    """).strip()


def _build_dashboard_layout_prompt(ctx: _GenerationContext, theme: str) -> str:
    spec = ctx.spec
    nav_items = "\n".join(f"  - {e.plural.lower() if hasattr(e, 'plural') else e.name.lower()+'s'}" for e in spec.entities)
    return textwrap.dedent(f"""
        Generate the dashboard layout component for the Next.js frontend.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === THEME ===
        {theme}

        === NAV ITEMS ===
        {nav_items}

        === REQUIREMENTS ===
        - File: frontend/src/app/(dashboard)/layout.tsx
        - Render a sidebar with navigation links for each entity section.
        - Include a top header bar with app name "{spec.app_name}", user avatar, and logout button.
        - Use "use client" directive.
        - Protect the layout — redirect to /login if no auth token found.
        - Apply {theme} visual theme with Tailwind CSS.
        - Output ONLY the TypeScript/TSX source — no markdown, no explanation.
    """).strip()


def _build_auth_pages_prompt(ctx: _GenerationContext, theme: str) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate login and register pages for the Next.js frontend.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === THEME ===
        {theme}

        === REQUIREMENTS ===
        - Generate TWO files separated by the comment "// === FILE: <path> ===" so they can be split:
            frontend/src/app/(auth)/login/page.tsx
            frontend/src/app/(auth)/register/page.tsx
        - Login page: email + password form, submit calls authApi.login(), stores token, redirects to dashboard.
        - Register page: name + email + password + confirm-password form with Zod validation.
        - Both pages: use React Hook Form, show error messages, loading state on submit.
        - Apply {theme} visual theme with Tailwind CSS centered card layout.
        - "use client" directive on both.
        - Output ONLY the TypeScript/TSX source — no markdown, no explanation.
    """).strip()


def _build_frontend_package_json_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate a package.json for a Next.js 14 + TypeScript + Tailwind CSS frontend project.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === REQUIREMENTS ===
        - File: frontend/package.json
        - name: "{spec.app_name.lower().replace(' ', '-')}-frontend"
        - Scripts: dev, build, start, lint, type-check
        - Dependencies (use latest stable versions):
            next, react, react-dom, typescript, @types/react, @types/node,
            tailwindcss, autoprefixer, postcss,
            react-hook-form, @hookform/resolvers, zod,
            lucide-react, clsx, class-variance-authority, tailwind-merge
        - devDependencies: eslint, eslint-config-next, @types/react-dom
        - Output ONLY the package.json content — no markdown, no explanation.
    """).strip()


def _build_tailwind_config_prompt(ctx: _GenerationContext, theme: str) -> str:
    return textwrap.dedent(f"""
        Generate a tailwind.config.ts for Next.js 14 with the {theme} theme.

        === REQUIREMENTS ===
        - File: frontend/tailwind.config.ts
        - Content paths: ./src/**/*.{{ts,tsx}}
        - Extend theme with a custom color palette appropriate for the {theme} theme.
        - Include font families: Inter for sans-serif body text.
        - Add borderRadius and boxShadow extensions.
        - Enable darkMode: "class"
        - Output ONLY the TypeScript config — no markdown, no explanation.
    """).strip()


def _build_frontend_dockerfile_prompt(ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate a production-ready multi-stage Dockerfile for a Next.js frontend.

        === REQUIREMENTS ===
        - File: frontend/Dockerfile
        - Stage 1 (deps): node:20-alpine, install dependencies with npm ci
        - Stage 2 (builder): copy deps and src, run npm run build
        - Stage 3 (runner): node:20-alpine, copy .next/standalone output, run server
        - Expose port 3000
        - Set NODE_ENV=production
        - Run as non-root user (nextjs uid 1001)
        - Output ONLY the Dockerfile content — no markdown, no explanation.
    """).strip()


def _build_tsconfig_prompt(ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate a tsconfig.json for a Next.js 14 project with TypeScript strict mode.

        === REQUIREMENTS ===
        - File: frontend/tsconfig.json
        - Extend next/typescript
        - Enable strict: true, strictNullChecks, noUncheckedIndexedAccess
        - Configure path aliases: "@/*" → "./src/*"
        - Output ONLY the JSON content — no markdown, no explanation.
    """).strip()


# ---------------------------------------------------------------------------
# Infrastructure prompt builders
# ---------------------------------------------------------------------------


def _build_docker_compose_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    has_redis = any("redis" in i.name.lower() for i in spec.integrations) or spec.tech_stack.cache == "Redis"
    has_celery = bool(spec.tech_stack.task_queue)
    return textwrap.dedent(f"""
        Generate a docker-compose.yml for the full stack application.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === REQUIREMENTS ===
        - File: docker-compose.yml
        - Services:
            db: postgres:16-alpine, with volume, env DATABASE_URL parts, healthcheck
            backend: build from ./backend, depends_on db{',' + ' redis' if has_redis else ''}, env_file .env, port 8000
            frontend: build from ./frontend, depends_on backend, port 3000, env NEXT_PUBLIC_API_URL
            {'redis: redis:7-alpine, port 6379, volume' if has_redis else ''}
            {'worker: same image as backend, command celery -A app.worker worker, depends_on redis, db' if has_celery else ''}
        - Use named volumes for postgres and redis data.
        - Use a shared network "app-network".
        - Include resource limits (mem_limit) on backend and frontend services.
        - Output ONLY the docker-compose.yml content — no markdown, no explanation.
    """).strip()


def _build_env_example_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    extra_vars = []
    for i in spec.integrations:
        extra_vars.extend(f"{v}=" for v in i.env_vars)
    extra = "\n".join(extra_vars)
    return textwrap.dedent(f"""
        Generate a .env.example file listing all environment variables needed by the application.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === INTEGRATION ENV VARS ===
        {extra or '(none beyond core)'}

        === REQUIREMENTS ===
        - File: .env.example
        - Core vars: DATABASE_URL, REDIS_URL, SECRET_KEY, ALLOWED_ORIGINS, ENVIRONMENT, DEBUG
        - JWT vars: ACCESS_TOKEN_EXPIRE_MINUTES, REFRESH_TOKEN_EXPIRE_DAYS
        - Frontend vars: NEXT_PUBLIC_API_URL
        - Include all integration env vars listed above.
        - Add helpful comments explaining what each var is for.
        - Output ONLY the .env.example content — no markdown, no explanation.
    """).strip()


def _build_gitignore_prompt(ctx: _GenerationContext) -> str:
    return textwrap.dedent(f"""
        Generate a comprehensive .gitignore file for a Python/FastAPI + Next.js monorepo.

        === REQUIREMENTS ===
        - File: .gitignore
        - Include: Python bytecode, venv, .env, __pycache__, .pytest_cache, .mypy_cache
        - Include: Node.js node_modules, .next, .cache, dist, build
        - Include: Docker volumes, IDE files (.vscode, .idea), OS files (.DS_Store, Thumbs.db)
        - Include: Alembic migration autogenerated files (but not the versions directory itself)
        - Output ONLY the .gitignore content — no markdown, no explanation.
    """).strip()


def _build_readme_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate a comprehensive README.md for the application described below.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === REQUIREMENTS ===
        - File: README.md
        - Sections: Overview, Features, Tech Stack, Prerequisites, Quick Start (Docker Compose),
          Local Development (Backend, Frontend), Environment Variables, API Documentation,
          Database Migrations, Testing, Deployment, Contributing, License.
        - Include real command examples with proper shell syntax.
        - Document all major API endpoints.
        - Include badges: build status, license, Python version, Node version.
        - Output ONLY the Markdown content — no markdown fences wrapping the whole file, no explanation.
    """).strip()


def _build_github_ci_prompt(ctx: _GenerationContext) -> str:
    spec = ctx.spec
    return textwrap.dedent(f"""
        Generate a GitHub Actions CI/CD workflow file.

        === SYSTEM SPEC ===
        {_spec_summary(spec)}

        === REQUIREMENTS ===
        - File: .github/workflows/ci.yml
        - Trigger on push to main and pull_request.
        - Jobs:
            backend-test: Python 3.11, install deps, run pytest with coverage
            frontend-test: Node 20, npm ci, run next build and lint
            docker-build: build both Docker images to verify they build successfully
        - Use GitHub Actions cache for pip and npm.
        - Fail fast on any test failure.
        - Output ONLY the YAML content — no markdown, no explanation.
    """).strip()


# ---------------------------------------------------------------------------
# Core engine
# ---------------------------------------------------------------------------


class CodeGeneratorV2:
    """
    Next-generation code generation engine for Ignara.

    Every file in the output project is generated by an LLM with full
    architectural context — no static template substitution.

    Key features:
    - Concurrent generation: files in the same dependency tier are generated
      in parallel using ``asyncio.gather``.
    - Dependency-aware ordering: files declare their dependencies so that
      models are available before schemas, schemas before CRUD, etc.
    - Smart context propagation: each prompt only receives interfaces
      relevant to the file being generated, not all 50+ interfaces.
    - Self-healing with full source: when a file has a syntax error the
      retry prompt includes both the error AND the broken source so the
      LLM can see exactly what to fix.
    """

    MAX_HEAL_ATTEMPTS = 3
    # Maximum concurrent LLM calls per batch (to avoid overwhelming the provider)
    MAX_CONCURRENCY = 6

    def __init__(self, provider: Optional[str] = None):
        self._client: BaseLLMClient = get_llm_client(provider) if provider else get_llm_client()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def generate(
        self,
        spec: SystemSpec,
        output_dir: str,
        theme: str = "Modern",
    ) -> GenerationResult:
        """
        Generate a complete, production-ready project from *spec*.

        Files are grouped into dependency tiers and each tier is generated
        concurrently.  Within a tier, up to :attr:`MAX_CONCURRENCY` files
        are generated in parallel.

        Args:
            spec:       The system specification produced by the Architect.
            output_dir: Filesystem path where the project will be written.
            theme:      Visual theme hint passed to frontend prompts.

        Returns:
            A :class:`GenerationResult` with file list, metrics, and warnings.
        """
        t_start = time.monotonic()
        ctx = _GenerationContext(spec=spec, output_dir=Path(output_dir), theme=theme)
        ctx.output_dir.mkdir(parents=True, exist_ok=True)

        plan = self._build_file_plan(ctx)
        tiers = self._topological_tiers(plan)

        generated_files: List[GeneratedFile] = []
        total_steps = len(plan)
        completed = 0

        for tier_idx, tier in enumerate(tiers):
            logger.info(
                "[tier %d/%d] Generating %d files concurrently",
                tier_idx + 1, len(tiers), len(tier),
            )

            # Limit concurrency with a semaphore
            sem = asyncio.Semaphore(self.MAX_CONCURRENCY)

            async def _gen_with_sem(fs: _FileSpec) -> GeneratedFile:
                async with sem:
                    return await self._generate_file(fs, ctx)

            results = await asyncio.gather(
                *[_gen_with_sem(fs) for fs in tier],
                return_exceptions=True,
            )

            for fs, result in zip(tier, results):
                completed += 1
                if isinstance(result, Exception):
                    logger.error("Failed to generate %s: %s", fs.relative_path, result)
                    ctx.warnings.append(f"Generation failed for {fs.relative_path}: {result}")
                    # Create a placeholder so downstream files aren't missing deps
                    generated_files.append(GeneratedFile(
                        path=fs.relative_path,
                        lines=0,
                        category=fs.category,
                        llm_generated=False,
                        heal_attempts=0,
                    ))
                else:
                    generated_files.append(result)
                logger.info(
                    "[%d/%d] %s",
                    completed, total_steps, fs.relative_path,
                )

        # Tally metrics
        backend_cats = {
            FileCategory.BACKEND_MODEL, FileCategory.BACKEND_SCHEMA,
            FileCategory.BACKEND_CRUD, FileCategory.BACKEND_ROUTE,
            FileCategory.BACKEND_CORE, FileCategory.BACKEND_DB,
            FileCategory.BACKEND_TEST, FileCategory.BACKEND_CONFIG,
        }
        frontend_cats = {
            FileCategory.FRONTEND_TYPE, FileCategory.FRONTEND_API,
            FileCategory.FRONTEND_COMPONENT, FileCategory.FRONTEND_PAGE,
            FileCategory.FRONTEND_CONFIG,
        }

        total_lines = sum(f.lines for f in generated_files)
        backend_files = sum(1 for f in generated_files if f.category in backend_cats)
        frontend_files = sum(1 for f in generated_files if f.category in frontend_cats)

        return GenerationResult(
            output_path=str(ctx.output_dir.resolve()),
            files=generated_files,
            total_files=len(generated_files),
            total_lines=total_lines,
            backend_files=backend_files,
            frontend_files=frontend_files,
            generation_time_seconds=round(time.monotonic() - t_start, 2),
            llm_calls_made=ctx.llm_calls,
            warnings=ctx.warnings,
        )

    async def generate_with_progress(
        self,
        spec: SystemSpec,
        output_dir: str,
        theme: str = "Modern",
    ) -> AsyncGenerator[ProgressEvent, None]:
        """
        Async generator variant that yields :class:`ProgressEvent` objects during generation.

        Uses the same concurrent tier-based approach as :meth:`generate`.
        """
        t_start = time.monotonic()
        ctx = _GenerationContext(spec=spec, output_dir=Path(output_dir), theme=theme)
        ctx.output_dir.mkdir(parents=True, exist_ok=True)

        plan = self._build_file_plan(ctx)
        tiers = self._topological_tiers(plan)
        total_steps = len(plan)
        generated_files: List[GeneratedFile] = []

        yield ProgressEvent(
            step="start",
            percentage=0.0,
            message=f"Generating {total_steps} files for {spec.app_name}",
        )

        completed = 0
        for tier in tiers:
            sem = asyncio.Semaphore(self.MAX_CONCURRENCY)

            async def _gen_with_sem(fs: _FileSpec) -> GeneratedFile:
                async with sem:
                    return await self._generate_file(fs, ctx)

            results = await asyncio.gather(
                *[_gen_with_sem(fs) for fs in tier],
                return_exceptions=True,
            )

            for fs, result in zip(tier, results):
                completed += 1
                pct = round((completed / total_steps) * 100, 1)
                if isinstance(result, Exception):
                    ctx.warnings.append(f"Generation failed for {fs.relative_path}: {result}")
                    generated_files.append(GeneratedFile(
                        path=fs.relative_path, lines=0, category=fs.category,
                        llm_generated=False, heal_attempts=0,
                    ))
                else:
                    generated_files.append(result)

                yield ProgressEvent(
                    step="generating",
                    percentage=pct,
                    current_file=fs.relative_path,
                    message=f"[{completed}/{total_steps}] {fs.description or fs.relative_path}",
                )

        yield ProgressEvent(
            step="complete",
            percentage=100.0,
            message=f"Done — {len(generated_files)} files generated in "
                    f"{round(time.monotonic() - t_start, 1)}s",
        )

    # ------------------------------------------------------------------
    # Dependency tier computation
    # ------------------------------------------------------------------

    @staticmethod
    def _topological_tiers(plan: List[_FileSpec]) -> List[List[_FileSpec]]:
        """Group *plan* into tiers respecting dependency order.

        Each tier contains files whose dependencies are all in earlier tiers.
        Files within a tier are independent and can be generated concurrently.
        """
        path_to_spec: Dict[str, _FileSpec] = {fs.relative_path: fs for fs in plan}
        completed: set[str] = set()
        remaining = list(plan)
        tiers: List[List[_FileSpec]] = []

        max_iterations = len(plan) + 1  # safety valve
        for _ in range(max_iterations):
            if not remaining:
                break
            # Find all files whose deps are satisfied
            ready = [
                fs for fs in remaining
                if all(d in completed for d in fs.depends_on)
            ]
            if not ready:
                # Circular or unresolvable deps — dump everything into one tier
                logger.warning(
                    "Cannot resolve dependencies for %d remaining files; "
                    "generating them in one batch.",
                    len(remaining),
                )
                tiers.append(remaining)
                break
            tiers.append(ready)
            completed.update(fs.relative_path for fs in ready)
            remaining = [fs for fs in remaining if fs.relative_path not in completed]

        return tiers

    # ------------------------------------------------------------------
    # File plan construction
    # ------------------------------------------------------------------

    def _build_file_plan(self, ctx: _GenerationContext) -> List[_FileSpec]:
        """
        Return the ordered list of files to generate.

        Order respects dependency flow so that later prompts can reference
        already-generated interfaces.
        """
        spec = ctx.spec
        plan: List[_FileSpec] = []

        # Collect entity names for dependency references
        entity_names_lower = [e.name.lower() for e in spec.entities]

        # ========== TIER 0: Foundation (no deps — all generated concurrently) ==========
        # DB base, DB session, core config, core security—and all __init__ stubs

        plan.append(_FileSpec(
            relative_path="backend/app/db/base.py",
            category=FileCategory.BACKEND_DB,
            prompt_builder=lambda c: _build_db_base_prompt(c),
            description="SQLAlchemy declarative base",
            depends_on=[],  # Tier 0
        ))
        plan.append(_FileSpec(
            relative_path="backend/app/db/session.py",
            category=FileCategory.BACKEND_DB,
            prompt_builder=lambda c: _build_db_session_prompt(c),
            description="Async DB session factory",
            depends_on=[],  # Tier 0
        ))
        plan.append(_FileSpec(
            relative_path="backend/app/core/config.py",
            category=FileCategory.BACKEND_CORE,
            prompt_builder=lambda c: _build_core_config_prompt(c),
            description="Pydantic settings / config",
            depends_on=[],  # Tier 0
        ))
        plan.append(_FileSpec(
            relative_path="backend/app/core/security.py",
            category=FileCategory.BACKEND_CORE,
            prompt_builder=lambda c: _build_core_security_prompt(c),
            description="Password hashing + JWT utils",
            depends_on=["backend/app/core/config.py"],
        ))
        plan.append(_FileSpec(
            relative_path="backend/app/core/auth.py",
            category=FileCategory.BACKEND_CORE,
            prompt_builder=lambda c: _build_core_auth_prompt(c),
            description="FastAPI auth dependencies",
            depends_on=["backend/app/core/security.py", "backend/app/db/session.py"],
        ))

        # __init__ files (static, no LLM needed, Tier 0)
        for init_path in [
            "backend/app/__init__.py",
            "backend/app/models/__init__.py",
            "backend/app/schemas/__init__.py",
            "backend/app/crud/__init__.py",
            "backend/app/api/endpoints/__init__.py",
            "backend/app/core/__init__.py",
            "backend/app/db/__init__.py",
            "backend/tests/__init__.py",
        ]:
            plan.append(_FileSpec(
                relative_path=init_path,
                category=FileCategory.BACKEND_CONFIG,
                prompt_builder=lambda c, p=init_path: f"# {p}\n",
                description=f"Package init: {init_path}",
                depends_on=[],  # Tier 0
            ))

        # ========== TIER 1: All entity models (concurrent, depend on DB base) ==========
        model_paths: List[str] = []
        for entity in spec.entities:
            ent = entity
            path = f"backend/app/models/{ent.name.lower()}.py"
            model_paths.append(path)
            plan.append(_FileSpec(
                relative_path=path,
                category=FileCategory.BACKEND_MODEL,
                prompt_builder=lambda c, e=ent: _build_model_prompt(e, c),
                description=f"SQLAlchemy model: {ent.name}",
                depends_on=["backend/app/db/base.py"],
            ))

        # ========== TIER 2: All entity schemas (concurrent, depend on their model) ==========
        schema_paths: List[str] = []
        for entity in spec.entities:
            ent = entity
            path = f"backend/app/schemas/{ent.name.lower()}.py"
            schema_paths.append(path)
            plan.append(_FileSpec(
                relative_path=path,
                category=FileCategory.BACKEND_SCHEMA,
                prompt_builder=lambda c, e=ent: _build_schema_prompt(e, c),
                description=f"Pydantic schemas: {ent.name}",
                depends_on=[f"backend/app/models/{ent.name.lower()}.py"],
            ))

        # ========== TIER 3: All CRUD modules (concurrent, depend on model + schema) ==========
        crud_paths: List[str] = []
        for entity in spec.entities:
            ent = entity
            path = f"backend/app/crud/{ent.name.lower()}.py"
            crud_paths.append(path)
            plan.append(_FileSpec(
                relative_path=path,
                category=FileCategory.BACKEND_CRUD,
                prompt_builder=lambda c, e=ent: _build_crud_prompt(e, c),
                description=f"CRUD operations: {ent.name}",
                depends_on=[
                    f"backend/app/models/{ent.name.lower()}.py",
                    f"backend/app/schemas/{ent.name.lower()}.py",
                ],
            ))

        # ========== TIER 4: All API routers (concurrent, depend on CRUD + auth) ==========
        router_paths: List[str] = []
        plan.append(_FileSpec(
            relative_path="backend/app/api/endpoints/auth.py",
            category=FileCategory.BACKEND_ROUTE,
            prompt_builder=lambda c: _build_auth_router_prompt(c),
            description="Auth router (login/register/refresh)",
            depends_on=["backend/app/core/auth.py", "backend/app/core/security.py"],
        ))
        router_paths.append("backend/app/api/endpoints/auth.py")

        for entity in spec.entities:
            ent = entity
            path = f"backend/app/api/endpoints/{ent.name.lower()}.py"
            router_paths.append(path)
            plan.append(_FileSpec(
                relative_path=path,
                category=FileCategory.BACKEND_ROUTE,
                prompt_builder=lambda c, e=ent: _build_route_prompt(e, c),
                description=f"API router: {ent.name}",
                depends_on=[
                    f"backend/app/crud/{ent.name.lower()}.py",
                    f"backend/app/schemas/{ent.name.lower()}.py",
                    "backend/app/core/auth.py",
                ],
            ))

        # ========== TIER 5: Router aggregator + main app (depend on all routers) ==========
        plan.append(_FileSpec(
            relative_path="backend/app/api/__init__.py",
            category=FileCategory.BACKEND_ROUTE,
            prompt_builder=lambda c: _build_main_router_prompt(c),
            description="Main API router aggregator",
            depends_on=router_paths,
        ))
        plan.append(_FileSpec(
            relative_path="backend/app/main.py",
            category=FileCategory.BACKEND_CORE,
            prompt_builder=lambda c: _build_main_app_prompt(c),
            description="FastAPI application entry point",
            depends_on=["backend/app/api/__init__.py"],
        ))

        # ========== Backend config files (Tier 0 — no code deps) ==========
        plan.append(_FileSpec(
            relative_path="backend/requirements.txt",
            category=FileCategory.BACKEND_CONFIG,
            prompt_builder=lambda c: _build_requirements_prompt(c),
            description="Python requirements",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path="backend/Dockerfile",
            category=FileCategory.BACKEND_CONFIG,
            prompt_builder=lambda c: _build_backend_dockerfile_prompt(c),
            description="Backend Dockerfile",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path="backend/alembic.ini",
            category=FileCategory.BACKEND_CONFIG,
            prompt_builder=lambda c: _build_alembic_ini_prompt(c),
            description="Alembic config",
            depends_on=[],
        ))

        # ========== TIER 5: Backend tests (depend on routes + CRUD) ==========
        for entity in spec.entities:
            ent = entity
            plan.append(_FileSpec(
                relative_path=f"backend/tests/test_{ent.name.lower()}.py",
                category=FileCategory.BACKEND_TEST,
                prompt_builder=lambda c, e=ent: _build_test_prompt(e, c),
                description=f"Tests: {ent.name}",
                depends_on=[
                    f"backend/app/api/endpoints/{ent.name.lower()}.py",
                    f"backend/app/schemas/{ent.name.lower()}.py",
                ],
            ))

        # ========== Frontend: Foundation (Tier 0 for types, depends on types for API) ==========
        plan.append(_FileSpec(
            relative_path="frontend/src/types/index.ts",
            category=FileCategory.FRONTEND_TYPE,
            prompt_builder=lambda c: _build_frontend_types_prompt(c),
            description="TypeScript type definitions",
            depends_on=[],  # Tier 0 for frontend
        ))
        plan.append(_FileSpec(
            relative_path="frontend/src/lib/api.ts",
            category=FileCategory.FRONTEND_API,
            prompt_builder=lambda c: _build_api_client_prompt(c),
            description="Typed API client",
            depends_on=["frontend/src/types/index.ts"],
        ))
        plan.append(_FileSpec(
            relative_path="frontend/src/components/ui/index.tsx",
            category=FileCategory.FRONTEND_COMPONENT,
            prompt_builder=lambda c: _build_ui_components_prompt(c, c.theme),
            description="Shared UI component library",
            depends_on=[],  # Tier 0 for frontend
        ))

        # ========== Frontend: Entity components (depend on types + UI + API) ==========
        for entity in spec.entities:
            ent = entity
            plan.append(_FileSpec(
                relative_path=f"frontend/src/components/{ent.name.lower()}/{ent.name}Components.tsx",
                category=FileCategory.FRONTEND_COMPONENT,
                prompt_builder=lambda c, e=ent: _build_entity_component_prompt(e, c, c.theme),
                description=f"Components: {ent.name}",
                depends_on=[
                    "frontend/src/types/index.ts",
                    "frontend/src/lib/api.ts",
                    "frontend/src/components/ui/index.tsx",
                ],
            ))

        # ========== Frontend: Pages (depend on entity components) ==========
        entity_component_paths = [
            f"frontend/src/components/{e.name.lower()}/{e.name}Components.tsx"
            for e in spec.entities
        ]
        plan.append(_FileSpec(
            relative_path="frontend/src/app/(auth)/login_register_pages.tsx",
            category=FileCategory.FRONTEND_PAGE,
            prompt_builder=lambda c: _build_auth_pages_prompt(c, c.theme),
            description="Login + register pages",
            depends_on=["frontend/src/components/ui/index.tsx", "frontend/src/lib/api.ts"],
        ))
        plan.append(_FileSpec(
            relative_path="frontend/src/app/(dashboard)/layout.tsx",
            category=FileCategory.FRONTEND_PAGE,
            prompt_builder=lambda c: _build_dashboard_layout_prompt(c, c.theme),
            description="Dashboard layout",
            depends_on=["frontend/src/components/ui/index.tsx"],
        ))
        for page in spec.pages:
            pg = page
            safe = pg.route.strip("/").replace("/", "_") or "home"
            plan.append(_FileSpec(
                relative_path=f"frontend/src/app/{safe}/page.tsx",
                category=FileCategory.FRONTEND_PAGE,
                prompt_builder=lambda c, p=pg: _build_page_prompt(p, c, c.theme),
                description=f"Page: {pg.title}",
                depends_on=entity_component_paths + [
                    "frontend/src/app/(dashboard)/layout.tsx",
                ],
            ))

        # ========== Frontend: Config (Tier 0 — no code deps) ==========
        plan.append(_FileSpec(
            relative_path="frontend/package.json",
            category=FileCategory.FRONTEND_CONFIG,
            prompt_builder=lambda c: _build_frontend_package_json_prompt(c),
            description="Frontend package.json",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path="frontend/tailwind.config.ts",
            category=FileCategory.FRONTEND_CONFIG,
            prompt_builder=lambda c: _build_tailwind_config_prompt(c, c.theme),
            description="Tailwind CSS config",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path="frontend/tsconfig.json",
            category=FileCategory.FRONTEND_CONFIG,
            prompt_builder=lambda c: _build_tsconfig_prompt(c),
            description="TypeScript config",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path="frontend/Dockerfile",
            category=FileCategory.FRONTEND_CONFIG,
            prompt_builder=lambda c: _build_frontend_dockerfile_prompt(c),
            description="Frontend Dockerfile",
            depends_on=[],
        ))

        # ========== Infrastructure (Tier 0 — no code deps) ==========
        plan.append(_FileSpec(
            relative_path="docker-compose.yml",
            category=FileCategory.INFRASTRUCTURE,
            prompt_builder=lambda c: _build_docker_compose_prompt(c),
            description="Docker Compose",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path=".env.example",
            category=FileCategory.INFRASTRUCTURE,
            prompt_builder=lambda c: _build_env_example_prompt(c),
            description="Environment variables example",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path=".gitignore",
            category=FileCategory.INFRASTRUCTURE,
            prompt_builder=lambda c: _build_gitignore_prompt(c),
            description=".gitignore",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path="README.md",
            category=FileCategory.INFRASTRUCTURE,
            prompt_builder=lambda c: _build_readme_prompt(c),
            description="Project README",
            depends_on=[],
        ))
        plan.append(_FileSpec(
            relative_path=".github/workflows/ci.yml",
            category=FileCategory.INFRASTRUCTURE,
            prompt_builder=lambda c: _build_github_ci_prompt(c),
            description="GitHub Actions CI/CD",
            depends_on=[],
        ))

        return plan

    # ------------------------------------------------------------------
    # File generation + validation + self-healing
    # ------------------------------------------------------------------

    async def _generate_file(
        self,
        file_spec: _FileSpec,
        ctx: _GenerationContext,
    ) -> GeneratedFile:
        """Generate, validate, and write a single file, self-healing on syntax errors.

        Thread-safe: uses an asyncio lock when updating shared context state
        so that concurrent generation doesn't corrupt the interfaces dict.
        """
        prompt = file_spec.prompt_builder(ctx)

        # Short-circuit for trivially static prompts (like __init__.py lines)
        if len(prompt) < 80 and not prompt.strip().endswith("?"):
            source = prompt
            heal_attempts = 0
        else:
            source, heal_attempts = await self._llm_generate_with_heal(
                prompt=prompt,
                relative_path=file_spec.relative_path,
                ctx=ctx,
            )

        # Write to disk
        dest = ctx.output_dir / file_spec.relative_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(source, encoding="utf-8")

        line_count = source.count("\n") + 1

        # Record a compact interface summary for use in subsequent prompts.
        # Use a lock since concurrent tasks may update the dict simultaneously.
        interface = self._extract_interface_summary(file_spec.relative_path, source)
        async with ctx._lock:
            ctx.generated_interfaces[file_spec.relative_path] = interface

        logger.debug("Wrote %s (%d lines)", file_spec.relative_path, line_count)

        return GeneratedFile(
            path=file_spec.relative_path,
            lines=line_count,
            category=file_spec.category,
            llm_generated=True,
            heal_attempts=heal_attempts,
        )

    async def _llm_generate_with_heal(
        self,
        prompt: str,
        relative_path: str,
        ctx: _GenerationContext,
    ) -> tuple[str, int]:
        """
        Call the LLM to generate *source* for *relative_path*.

        On validation failure, retry up to :attr:`MAX_HEAL_ATTEMPTS` times.
        The retry prompt now includes the broken source code AND the error
        message so the LLM can see exactly what went wrong.

        Returns a (source_code, heal_attempt_count) tuple.
        """
        heal_count = 0
        current_prompt = prompt

        for attempt in range(self.MAX_HEAL_ATTEMPTS + 1):
            source = await self._call_llm(current_prompt, ctx)
            source = _strip_code_fences(source)

            error = _validate_file(relative_path, source)
            if error is None:
                return source, heal_count

            heal_count = attempt + 1
            if heal_count > self.MAX_HEAL_ATTEMPTS:
                msg = (
                    f"File {relative_path} still has syntax errors after "
                    f"{self.MAX_HEAL_ATTEMPTS} heal attempts: {error}"
                )
                logger.warning(msg)
                async with ctx._lock:
                    ctx.warnings.append(msg)
                return source, heal_count  # return best-effort

            logger.info(
                "Healing %s (attempt %d/%d): %s",
                relative_path, heal_count, self.MAX_HEAL_ATTEMPTS, error,
            )

            # Include the broken source so the LLM can see what to fix,
            # truncated to avoid exceeding context limits.
            source_preview = source[:4000] if len(source) > 4000 else source
            current_prompt = (
                f"{prompt}\n\n"
                f"IMPORTANT — your previous response had this syntax error:\n"
                f"  {error}\n\n"
                f"Here is the broken code you produced:\n"
                f"```\n{source_preview}\n```\n\n"
                f"Fix the issue and output the complete corrected file. "
                f"Output ONLY the raw source code with no markdown fences."
            )

        # Unreachable in practice, but satisfies type checker
        return source, heal_count  # type: ignore[return-value]

    async def _call_llm(self, prompt: str, ctx: Optional[_GenerationContext] = None) -> str:
        """
        Dispatch a single LLM completion call asynchronously.

        The underlying ``client.complete()`` is synchronous; we use
        ``asyncio.to_thread`` so that it does not block the event loop.

        If *ctx* is provided, increments the LLM call counter thread-safely.
        """
        response = await asyncio.to_thread(
            self._client.complete,
            prompt,
            CODEGEN_SYSTEM_PROMPT,
            8192,   # max_tokens — allow large files
            0.2,    # temperature — low for precision
            False,  # json_mode
        )
        if ctx is not None:
            async with ctx._lock:
                ctx.llm_calls += 1
        return response.content

    # ------------------------------------------------------------------
    # Interface extraction (for context propagation)
    # ------------------------------------------------------------------

    @staticmethod
    def _extract_interface_summary(relative_path: str, source: str) -> str:
        """
        Produce a compact summary of a file's public API for use in subsequent prompts.

        For Python files: extracts imports, class definitions (with bases and methods),
        and top-level function signatures with full type annotations.
        For TypeScript files: extracts exported symbols.
        For other files: returns a brief content preview.
        """
        ext = Path(relative_path).suffix.lower()
        lines_preview: List[str] = []

        if ext == ".py":
            try:
                tree = ast.parse(source)
                # Collect imports (useful for understanding what's available)
                for node in ast.iter_child_nodes(tree):
                    if isinstance(node, ast.ImportFrom):
                        names = ", ".join(a.name for a in node.names[:5])
                        if node.module:
                            lines_preview.append(f"from {node.module} import {names}")
                    if len(lines_preview) >= 5:
                        break

                # Collect top-level classes and functions
                for node in ast.iter_child_nodes(tree):
                    if isinstance(node, ast.ClassDef):
                        bases = [
                            (b.id if isinstance(b, ast.Name) else
                             getattr(b, 'attr', '') if isinstance(b, ast.Attribute) else "")
                            for b in node.bases
                        ]
                        lines_preview.append(f"class {node.name}({', '.join(filter(None, bases))})")
                        # Add key method signatures (up to 8)
                        method_count = 0
                        for child in ast.iter_child_nodes(node):
                            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                                args = [a.arg for a in child.args.args if a.arg != 'self']
                                prefix = "async " if isinstance(child, ast.AsyncFunctionDef) else ""
                                lines_preview.append(f"  {prefix}def {child.name}({', '.join(args)})")
                                method_count += 1
                                if method_count >= 8:
                                    break
                    elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        args = [a.arg for a in node.args.args]
                        prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
                        lines_preview.append(f"{prefix}def {node.name}({', '.join(args)})")

                    if len(lines_preview) >= 30:
                        break
            except SyntaxError:
                lines_preview = [source[:400]]

        elif ext in (".ts", ".tsx", ".js", ".jsx"):
            for line in source.splitlines()[:80]:
                stripped = line.strip()
                if stripped.startswith("export") or stripped.startswith("interface "):
                    lines_preview.append(stripped[:150])
                if len(lines_preview) >= 20:
                    break

        else:
            # Generic: first 5 non-empty lines
            for line in source.splitlines():
                if line.strip():
                    lines_preview.append(line[:120])
                if len(lines_preview) >= 5:
                    break

        return "\n".join(lines_preview) if lines_preview else "(empty)"


# ---------------------------------------------------------------------------
# Helper: strip markdown code fences from LLM output
# ---------------------------------------------------------------------------


def _strip_code_fences(source: str) -> str:
    """
    Remove leading/trailing markdown code fences that some LLMs add despite instructions.

    Handles patterns::

        ```python
        ...code...
        ```

        ```
        ...code...
        ```
    """
    s = source.strip()

    # Remove opening fence (with optional language tag)
    if s.startswith("```"):
        first_newline = s.find("\n")
        if first_newline != -1:
            s = s[first_newline + 1:]

    # Remove closing fence
    if s.endswith("```"):
        s = s[: s.rfind("```")].rstrip()

    return s
