// This file is auto-generated by the App-Builder Contract System
// It must match the backend Pydantic models.

export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  company?: string;
  industry?: string;
  website?: string;
  lead_score?: number;
  last_contact_date?: string;
  notes?: string;
  preferred_contact_method?: string;
  customer_segment?: string;
  total_purchases?: number;
  lifetime_value?: number;
  created_at?: string;
}
